export const ORDER_COUNT_REQUEST = 'ORDER_COUNT_REQUEST'
export const ORDER_COUNT_SUCCESS = 'ORDER_COUNT_SUCCESS'
export const ORDER_COUNT_FAIL = 'ORDER_COUNT_FAIL'

export const THEATER_COUNT_REQUEST = 'THEATER_COUNT_REQUEST'
export const THEATER_COUNT_SUCCESS = 'THEATER_COUNT_SUCCESS'
export const THEATER_COUNT_FAIL = 'THEATER_COUNT_FAIL'

export const USER_COUNT_REQUEST = 'USER_COUNT_REQUEST'
export const USER_COUNT_SUCCESS = 'USER_COUNT_SUCCESS'
export const USER_COUNT_FAIL = 'USER_COUNT_FAIL'

export const MOVIE_COUNT_REQUEST = 'MOVIE_COUNT_REQUEST'
export const MOVIE_COUNT_SUCCESS = 'MOVIE_COUNT_SUCCESS'
export const MOVIE_COUNT_FAIL = 'MOVIE_COUNT_FAIL'

export const COUNT_REQUEST = 'COUNT_REQUEST'
export const COUNT_SUCCESS = 'COUNT_SUCCESS'
export const COUNT_FAIL = 'COUNT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'