export const ADMIN_MOVIES_REQUEST = 'ADMIN_MOVIES_REQUEST'
export const ADMIN_MOVIES_SUCCESS = 'ADMIN_MOVIES_SUCCESS'
export const ADMIN_MOVIES_FAIL = 'ADMIN_MOVIES_FAIL'

export const ALL_MOVIES_REQUEST = 'ALL_MOVIES_REQUEST'
export const ALL_MOVIES_SUCCESS = 'ALL_MOVIES_SUCCESS'
export const ALL_MOVIES_FAIL = 'ALL_MOVIES_FAIL'

export const NEW_MOVIE_REQUEST = 'NEW_MOVIE_REQUEST'
export const NEW_MOVIE_SUCCESS = 'NEW_MOVIE_SUCCESS'
export const NEW_MOVIE_RESET = 'NEW_MOVIE_RESET'
export const NEW_MOVIE_FAIL = 'NEW_MOVIE_FAIL'

export const DELETE_MOVIE_REQUEST = 'DELETE_MOVIE_REQUEST'
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS'
export const DELETE_MOVIE_RESET = 'DELETE_MOVIE_RESET'
export const DELETE_MOVIE_FAIL = 'DELETE_MOVIE_FAIL'

export const UPDATE_MOVIE_REQUEST = 'UPDATE_MOVIE_REQUEST'
export const UPDATE_MOVIE_SUCCESS = 'UPDATE_MOVIE_SUCCESS'
export const UPDATE_MOVIE_RESET = 'UPDATE_MOVIE_RESET'
export const UPDATE_MOVIE_FAIL = 'UPDATE_MOVIE_FAIL'

export const MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_REQUEST'
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS'
export const MOVIE_DETAILS_FAIL = 'MOVIE_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'