export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'

export const MY_ORDERS_REQUEST = 'MY_ORDERS_REQUEST'
export const MY_ORDERS_SUCCESS = 'MY_ORDERS_SUCCESS'
export const MY_ORDERS_FAIL = 'MY_ORDERS_FAIL'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const U_UPDATE_ORDER_REQUEST = 'U_UPDATE_ORDER_REQUEST'
export const U_UPDATE_ORDER_SUCCESS = 'U_UPDATE_ORDER_SUCCESS'
export const U_UPDATE_ORDER_RESET = 'U_UPDATE_ORDER_RESET'
export const U_UPDATE_ORDER_FAIL = 'U_UPDATE_ORDER_FAIL'

export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST'
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS'
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL'
export const ORDER_DELETE_RESET = 'ORDER_DELETE_RESET'




//admin--------------------------------------------------------------------
export const ALL_ORDERS_REQUEST = 'ALL_ORDERS_REQUEST'
export const ALL_ORDERS_SUCCESS = 'ALL_ORDERS_SUCCESS'
export const ALL_ORDERS_FAIL = 'ALL_ORDERS_FAIL'

export const A_UPDATE_ORDER_REQUEST = 'A_UPDATE_ORDER_REQUEST'
export const A_UPDATE_ORDER_SUCCESS = 'A_UPDATE_ORDER_SUCCESS'
export const A_UPDATE_ORDER_RESET = 'A_UPDATE_ORDER_RESET'
export const A_UPDATE_ORDER_FAIL = 'A_UPDATE_ORDER_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'