export const ADMIN_THEATERS_REQUEST = 'ADMIN_THEATERS_REQUEST'
export const ADMIN_THEATERS_SUCCESS = 'ADMIN_THEATERS_SUCCESS'
export const ADMIN_THEATERS_FAIL = 'ADMIN_THEATERS_FAIL'

export const ALL_THEATERS_REQUEST = 'ALL_THEATERS_REQUEST'
export const ALL_THEATERS_SUCCESS = 'ALL_THEATERS_SUCCESS'
export const ALL_THEATERS_FAIL = 'ALL_THEATERS_FAIL'

export const NEW_THEATER_REQUEST = 'NEW_THEATER_REQUEST'
export const NEW_THEATER_SUCCESS = 'NEW_THEATER_SUCCESS'
export const NEW_THEATER_RESET = 'NEW_THEATER_RESET'
export const NEW_THEATER_FAIL = 'NEW_THEATER_FAIL'

export const DELETE_THEATER_REQUEST = 'DELETE_THEATER_REQUEST'
export const DELETE_THEATER_SUCCESS = 'DELETE_THEATER_SUCCESS'
export const DELETE_THEATER_RESET = 'DELETE_THEATER_RESET'
export const DELETE_THEATER_FAIL = 'DELETE_THEATER_FAIL'

export const UPDATE_THEATER_REQUEST = 'UPDATE_THEATER_REQUEST'
export const UPDATE_THEATER_SUCCESS = 'UPDATE_THEATER_SUCCESS'
export const UPDATE_THEATER_RESET = 'UPDATE_THEATER_RESET'
export const UPDATE_THEATER_FAIL = 'UPDATE_THEATER_FAIL'

export const THEATER_DETAILS_REQUEST = 'THEATER_DETAILS_REQUEST'
export const THEATER_DETAILS_SUCCESS = 'THEATER_DETAILS_SUCCESS'
export const THEATER_DETAILS_FAIL = 'THEATER_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'